### ISSUE TITLE
error when using fragment option

### ISSUE THREAD

**Issue by moees** [BayanGroup/nutch-custom-search#11]
Hi i'm testing the fragment option to extract several documents from one given page. i keep getting the following exception using nutch and UrlTester.java

Extracting from http://www.domain.com/test.htm
java.lang.RuntimeException: Url field for a document or fragment can not be null. Current url: http://www.domani.com/test.htm
	at ir.co.bayan.simorq.zal.extractor.model.Fragment.insertSpecialFields(Fragment.java:100)
	at ir.co.bayan.simorq.zal.extractor.model.Fragment.extract(Fragment.java:50)
	at ir.co.bayan.simorq.zal.extractor.model.Document.extract(Document.java:257)
	at ir.co.bayan.simorq.zal.extractor.model.Document.extract(Document.java:236)
	at ir.co.bayan.simorq.zal.extractor.core.ExtractEngine.extract(ExtractEngine.java:114)
	at ir.co.bayan.simorq.zal.extractor.util.UrlTester.testUrl(UrlTester.java:60)
	at ir.co.bayan.simorq.zal.extractor.util.UrlTester.main(UrlTester.java:35)

I'm using the test.htm file provided in zal.extractor/src/test/resources/ and the config example used in your documentation:

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir http://raw.github.com/BayanGroup/nutch-custom-search/master/zal.extractor/src/main/resources/extractors.xsd">
<fields>
<field name="url" />
<field name="content" />
</fields>
<documents>
<document url="test.htm" engine="css">
    <fragment root=".doc">
        <extract-to field="url">
            <first>
                <attribute name="href">
                    <expr value="a"/>
                 </attribute>
            </first>
        </extract-to>
        <extract-to field="content">
            <text>
                <expr value="a" />
            </text>
        </extract-to>
    </fragment>
</document>
</documents>
</config>
Can you please tell me if i'm doing any thing wrong.

Thanks in advance.

**Comment by tahagh** [comment]
Since each fragment is going to be a distinct document recognizable by nutch, it is required to have a field named url inside your fragment like this:

<fragment root=".doc">
        <extract-to field="url">
            ... some functions to extract your desired url for this fragment ....
        </extract-to>
...
</fragment>

I will update the documentation to stress this fact. Thanks for the question.

**Comment by moees** [comment]
Problem resolved. Thank you.

**Comment by moees** [comment]
Hi Taha.

I posted an issue on your git a few days ago.

I have a problem using the fragment function under nutch, your example 
in the documentation works fine with UrlTester.java, but it doesn't work 
with nutch (i dont get any extracted documents). I'm i doing anything 
wrong? As i know nutch uses the page url as a key to store the documents 
in solr, solr doesn't support storing hierarchical documents so it would 
be difficult to store several documents with subfields under the same 
page. Is this is a reason preventing using fragments under nutch.

Thanks.

**Comment by richard-lund** [comment]
I have the same issue with extracting fragments, but a little more information about why they're not getting through Nutch and into Solr.

It looks like all of the fragment documents are created with the same digest as the parent document. This is the checksum that Solr uses to remove duplicates, therefore they get cleaned up as part of that operation. If one is quick and grabs the contents of the index after indexing has completed but before de-duplication is run, it's possible to see the content - this shows me the following: (note that `segment`, `digest` and `contentLength` are all the same as the parent)

    {
        "content":"",
        "title":"Product - Quotes",
        "segment":"20150514075259",
        "boost":1.0,
        "digest":"d8cdc931c413cb5697ff342bc0efc799",
        "tstamp":"2015-05-14T06:53:29.338Z",
        "type":"text/html",
        "date":"2015-05-14T06:53:29.338Z",
        "contentLength":"21181",
        "id":"http://example.com/products/product-quotes.aspx",
        "url":"http://example.com/products/product-quotes.aspx",
        "_version_":1501127257580634112},
    {
        "content":"997",
        "title":"Product|managerial|3year|1000",
        "segment":"20150514075259",
        "boost":0.0,
        "digest":"d8cdc931c413cb5697ff342bc0efc799",
        "tstamp":"1970-01-01T00:00:00Z",
        "type":"text/html",
        "date":"1970-01-01T00:00:00Z",
        "contentLength":"21181",
        "id":"http://example.com/products/product-quotes/quote/product-product/class-managerial/frequency-3year/income-1000",
        "url":"http://example.com/products/product-quotes/quote/product-product/class-managerial/frequency-3year/income-1000",
        "_version_":1501127257687588864},
    {
        "content":"1246",
        "title":"Product|managerial|3year|1250",
        "segment":"20150514075259",
        "boost":0.0,
        "digest":"d8cdc931c413cb5697ff342bc0efc799",
        "tstamp":"1970-01-01T00:00:00Z",
        "type":"text/html",
        "date":"1970-01-01T00:00:00Z",
        "contentLength":"21181",
        "id":"http://example.com/products/product-quotes/quote/product-product/class-managerial/frequency-3year/income-1250",
        "url":"http://example.com/products/product-quotes/quote/product-product/class-managerial/frequency-3year/income-1250",
        "_version_":1501127257691783168},
    // ... etc with other fragment documents

**Comment by tahagh** [comment]
Yes, if you are using the nutch deduplication you should pass a unique content for each of your fragments as [discussed here](https://github.com/BayanGroup/nutch-custom-search/issues/14#issuecomment-73380379).
