### ISSUE TITLE
corrupt distribution zip

### ISSUE THREAD

**Issue by rugbymauri** [BayanGroup/nutch-custom-search#13]
Hello 

the distribution zip-file seems to be corrupt.

**Comment by tahagh** [comment]
I don't see any problem with it.

**Comment by rugbymauri** [comment]
Strage, perhaps it a OS problem, im using Ubuntu 14.10. 
I find out that extracting the ZIP with the CLI-Tool worked, but i got some warnings:

> Archive:  zal.extractor-0.0.3-distribution.zip
> file #1 (extractor/):
>          mismatch between local and central GPF bit 11 ("UTF-8"),
>          continuing with central flag (IsUTF8 = 1)
>    creating: extractor/
>   inflating: extractor/plugin.xml    
> file #3 (extractor/xercesImpl-2.9.1.jar):
>          mismatch between local and central GPF bit 11 ("UTF-8"),
>          continuing with central flag (IsUTF8 = 1)
>  extracting: extractor/xercesImpl-2.9.1.jar  
> file #4 (extractor/xml-apis-1.4.01.jar):
>          mismatch between local and central GPF bit 11 ("UTF-8"),
>          continuing with central flag (IsUTF8 = 1)
>  extracting: extractor/xml-apis-1.4.01.jar  
> file #5 (extractor/jsoup-1.8.1.jar):
>          mismatch between local and central GPF bit 11 ("UTF-8"),
>          continuing with central flag (IsUTF8 = 1)
>  extracting: extractor/jsoup-1.8.1.jar  
> file #6 (extractor/slf4j-api-1.7.5.jar):
>          mismatch between local and central GPF bit 11 ("UTF-8"),
>          continuing with central flag (IsUTF8 = 1)
>  extracting: extractor/slf4j-api-1.7.5.jar  
> file #7 (extractor/commons-lang3-3.1.jar):
>          mismatch between local and central GPF bit 11 ("UTF-8"),
>          continuing with central flag (IsUTF8 = 1)
>  extracting: extractor/commons-lang3-3.1.jar  
> file #8 (extractor/nekohtml-1.9.21.jar):
>          mismatch between local and central GPF bit 11 ("UTF-8"),
>          continuing with central flag (IsUTF8 = 1)
>  extracting: extractor/nekohtml-1.9.21.jar  
> file #9 (extractor/zal.extractor-0.0.3.jar):
>          mismatch between local and central GPF bit 11 ("UTF-8"),
>          continuing with central flag (IsUTF8 = 1)
>  extracting: extractor/zal.extractor-0.0.3.jar  
>

**Comment by tahagh** [comment]
The zip file is created using the maven archive plugin. There might be some issue with it that I don't know. Thanks for the report anyway.
