### ISSUE TITLE
Return img alt and text

### ISSUE THREAD

**Issue by phranq** [BayanGroup/nutch-custom-search#14]
Hello,

I'm using your plugin to crawl a forum and index it in solr.
I have having issues to retrieve messages that contain only a smiley (no pure text, just some '< p>< i m g  s r c = " s m i l e y . g i f "  a l t = " :h e l l o: " > < / p > ' )

My extractor.xml looks like this:

    <document url="http://myforum.com" engine="css">
	<extract-to field="name">
		<text>
			<expr value=".name" />
		</text>
	</extract-to>

	<extract-to field="message">
		<text>
			<expr value=".message" />
		</text>
	</extract-to>
    </document>

If i try to index such a message, of course my metadata "message" stays empty and is not created. This is an issue for me, since every "name" should have a "message" associated. And now if I look at my solr I'll have something like this :

Let's say name2 posts only a smiley, with no text:

< name>
name1
name2
name3
< /name>

< message>
hello from name1
hello from name 3
< /message>

Of course what I would like to have is 

< name>
name1
name2
name3
< /name>

< message>
hello from name1
:hello:
hello from name 3
< /message>

If there a way to retrieve the raw html code of my forum post ? or better the alt of the smiley that was used + the text ?

**Comment by tahagh** [comment]
> If there a way to retrieve the raw html code of my forum post ? or better the alt of the smiley that was used + the text ?

Unfortunately no but both of your options can be implemented with a little effort. For the retrieval of raw html code, you can change the getText method of CssEvaluator to call html() method of nodes instead of calling their text() method. Or as a more general solution, one can add an attribute to the text method which indicates which one should be used. I'm going to implement this in the near future but might take some time. 
Your second option is very specific but since this solution is clearly better suits you, I suggest you to implement it. You should implement a new function, say textOrAttribute, based on the codes of text and attribute functions. I don't think it takes a lot of time from you.

**Comment by phranq** [comment]
Thank you for your interesting feedback. I'll try to change this getText method.
And by the way thank you for this great plugin.

**Comment by phranq** [comment]
I didn't have too much time but calling the html() function of an Element already helps a lot to have something very usefull for me.

Also I was trying to use the Fragment to put in Solr every user forum post as a single document, but I could not manage.
I guess this is "normal" behaviour like raised by issue 11: https://github.com/BayanGroup/nutch-custom-search/issues/11

Could you confirm this ?

Thank you very much!

**Comment by tahagh** [comment]
No, I still think that this should be possible, as long as you provide a unique url for each of your fragments. My suggestion is to put the log level to debug, an see in which part something goes wrong.

**Comment by phranq** [comment]
Actually I can't manage to put different urls for my fragment, because I need to rebuild the urls myself. I can only extract part of this url from css selector.

I now use something like this:

     <fragment root=".single-post">
		<extract-to field="url">
		    <attribute name="post-id">
				<expr value="div"/>
			</attribute>
		</extract-to>

Using this my url field contains a unique number (like 405925004 for instance) which is only a part of the complete url of the fragment. So then I see in Nutch:

    Parsed (0ms):405925004
    Parsed (0ms):405925092
    Skipping 405924052           :java.net.MalformedURLException: no protocol: 405925004
    Skipping 405924684           :java.net.MalformedURLException: no protocol: 405925092

How can I change my extractor file to extract in my url field something like

`http://forum.com/post-id/<attribute name="post-id"><expr value="div"/></attribute>` 
and not only `<attribute name="post-id"><expr value="div"/></attribute>`

Thank you for you help... and patience ! :+1:

**Comment by tahagh** [comment]
I think you can use something like this:

```
<concat delimiter="">
    <constant value="http://forum.com/post-id/" />
    <attribute name="post-id">...</attribute>
</concat>
```

**Comment by phranq** [comment]
It works, thanks!

Well at least the fragments work, but once it gets indexed, then it gets deleted. 
In the following example I was indexing my forum page + the 14 forum posts on the page. Everything gets indexed, and then all my 14 messages are automatically cleaned

2015-02-07 22:35:02,558 INFO  solr.SolrIndexWriter - Indexing 15 documents
2015-02-07 22:35:05,065 INFO  indexer.CleaningJob - CleaningJob: deleted a total of 14 documents

It seems like something makes nutch clean all my entries...

**Comment by tahagh** [comment]
The cleaning job removes duplicate (and 404) pages. So I guess you should also pass a unique content for each of your fragments like this:

<fragment ...>
   <extract-to field="url">...</extract-to>
   <extract-to field="content">...</extract-to>
</fragment>
