### ISSUE TITLE
Using for-each in an HTML Page.

### ISSUE THREAD

**Issue by jaychakra** [BayanGroup/nutch-custom-search#17]
Hi I have setup the extractor as per the documentation of yours. But I am confused in using for-each, I am missing the root as the hadoop logs says.  __Attribute 'root' must appear on element 'for-each'.]__

It would be very helpful if you add an example for the usage of for-each

**Comment by tahagh** [comment]
You right, the help is still need a lot more explanations.
And about for-each: When you write an expression like <expr value=".foo" />, the value of this expression is computed according to the current root which is by default is the root element of your html or xml document. So the expression <expr value=".foo" /> actually means find all descendants of the current root  with the class foo. In some occasions, you might change this behavior and evaluate the expression against a different root (the use case is very limited and I'm curious why you need it anyway). In this case, you can use for-each. For example:

```xml
<for-each root=".bar">
   <text>
      <expr value=".foo"/>
   </text>
</for-each> 
```

Now, for each element with the bar class, the expression <expr value=".foo"/> is evaluated once with that element as the root and finds all of its descendants with the foo class. Clearly, in this simple example one can instead write something like <text><expr value=".bar .foo"></text>.

**Comment by jaychakra** [comment]
Hi Tahagh,
Thanks for a quick reply.
I have used the above method which you specified. It worked but the problem which I am facing is after using foreach I can just evaluate only one variable and all the values are getting stored as space separated but I need it in something like the multivariable of solr.

Let me explain the use case.
Suppose we have a structure like this
```html
<div class="stock">
    <div class="item">
        Gold
        <span class="date">21-10-2015</span>
        <span class="price">a</span>
        <span class="date">22-10-2015</span>
        <span class="price">b</span>
        ...
        ...
    </div>
</div>
```

So I was wondering how for-each can solve this issue of keeping dates in an array and price in an array. So that I can use these data tp predict the price in future or can deduce some relevant info after indexing.

**Comment by tahagh** [comment]
I have a little difficulty to understand what exactly what you want: Suppose you have 100 items in your stock. Do you want to store the date and price arrays of all items in a single document but in separate variables? (so at end you must have 200 variables)? Is this acceptable for you: store each item as a separate document in solr and each document has two multi-value variables, date and price. If this is your case you can achieve it with extractor using fragments like this:

```xml
<fields>
  <field name="date" multi="true"/>
  <field name="price" multi="true"/>
</fields>
<documents>
  <document url=".">
    <fragment root=".item">
      <extract-to field="date">
           <text>
                <expr value=".date"/>
           </text>
    </extract-to>
    <extract-to field="price">
           <text>
                <expr value=".price"/>
           </text>
    </extract-to>
    <extract-to field="url">
        <!-- some unique value -->
    </extract-to>
    </fragment>
  </document>
</documents>
```
