### ISSUE TITLE
Bug in document inheritance?

### ISSUE THREAD

**Issue by raisindetre** [BayanGroup/nutch-custom-search#18]
Hi,

I may be misunderstanding your instructions but I am unable to get document inheritance working more than 1 level deep. I have a chain that looks like this:

<document url="." id="outlinks">
<document url="." inherits="outlinks" id="base">
<document url="^http://www\.test\.co\.uk.+" inherits="base" id="uk">
<document url="^http://www\.test\.com.+" inherits="base" id="us">

I would expect the parse chain to always include the first two documents and choose between the last two, but instead only the first two documents appear to be run - no fields from the latter two are included. But if I remove either of the last two - the remaining document is parsed for a matching domain.

Is this expected behaviour? Should I be able to get this to work as I want it to?

Thanks,

**Comment by raisindetre** [comment]
Comment removed my quoted code - document declarations in inheritance chain looks like this (they are well formed and validate - I've just shown opening tags here for brevity):

`<document id="outlinks">`
`<document id="base" url="." inherits="outlinks">`
`<document id="uk" url="^http://www\.test\.co\.uk" inherits="base">`
`<document id="us" url="^http://www\.test\.com" inherits="base">`

**Comment by tahagh** [comment]
Engine works by finding the first matched document. In your example, the second document with url="." always get matched with any url so next documents will be ignored.

**Comment by raisindetre** [comment]
Thanks - got there in the end by removing url matches for the top levels of the inheritance chain that I wanted to apply to all docs parsed. I also found that I needed to declare the parsing engine in all document statements to get things working correctly.
