### ISSUE TITLE
What subset of Jsoup css selector is supported?

### ISSUE THREAD

**Issue by ChanderG** [BayanGroup/nutch-custom-search#22]
I am having trouble running some queries that run perfectly on http://try.jsoup.org/.

I am using it with Nutch.

**Comment by tahagh** [comment]
We don't restrict any selectors. I think the problem might be something else. Would you please elaborate more?

**Comment by ChanderG** [comment]
Ok. The problem is not in the selector. Just verified.

Say, I need to get the main product name from an [Amazon](http://www.amazon.com/Way-Kings-Stormlight-Archive/dp/0765365278/) page. Tried various combinations, but it simply does not match. Just tried the same selector ( "body div h1") on [Flipkart](http://www.flipkart.com/way-kings-english/p/itme53ktw7zg6rxb) (Indian competitor to Amazon, so a very similar organization of html) and it's working fine.

Simple selectors on Amazon like "body" are working. So it is not a problem with robots.txt. 

Also, all urls in seed.txt are parsed in the first iteration in Nutch. Except Amazon. For some reason, it alone (irrespective of the order of urls in the file) is being parsed in the second iteration.

Also, opened Amazon page's source code. It looks very strange.

Any ideas?

**Comment by tahagh** [comment]
Just tested with url tester. The "body div h1" works perfectly on your
amazon page. One source of problem might be the nutch content truncation.
If the size of a page is above a certain limit, nutch truncates the
content.

**Comment by ChanderG** [comment]
Thanks a lot. That was the source of the problem.

**Comment by ChanderG** [comment]
Sorry. I did not know that I had to close the issue. Thanks again,
