### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by galvinm** [BayanGroup/nutch-custom-search#23]
Can nutch-custom-search extract images?

**Comment by tahagh** [comment]
No it only parses html/xml files extracted by nutch.

**Comment by AndraIonescu** [comment]
You said it only parses html/xml, but I couldn't get the image url from the <img> tag. How can I do that?

**Comment by tahagh** [comment]
a rule like this should do the work:

<attribute name="src">
    <expr value="img"/>
</attribute>
