### ISSUE TITLE
cannot testUrl

### ISSUE THREAD

**Issue by virivigio** [BayanGroup/nutch-custom-search#26]
Since I'm not seeing the expected extracted values i tried the UrlTester but it seems unwilling to work:

root:~/apache-nutch-1.9/plugins/extractor# pwd
/root/apache-nutch-1.9/plugins/extractor

root:~/apache-nutch-1.9/plugins/extractor#  java -jar zal.extractor-0.0.3.jar ir.co.bayan.simorq.zal.extractor.util.UrlTester "file:/root/saved.html" "/root/apache-nutch-1.9/conf/cineca-extractor.xml"
UrlTester <url> <location-of extractors.xml>
e.g. UrlTester http://www.google.com /conf/extractors.xml

what's wrong?
thank you

**Comment by virivigio** [comment]
ok I worked it out playing with classpath and grabbing an online resource instead of a local file. maybe something with the file url has to be checked

root:~/apache-nutch-1.9/plugins/extractor# java -cp "*:../../lib/*" ir.co.bayan.simorq.zal.extractor.util.UrlTester "http://www.iluoghidelsociale.it/?page_id=1522" "/root/apache-nutch-1.9/conf/cineca-extractor.xml"

Read config form /root/apache-nutch-1.9/conf/cineca-extractor.xml
Extracting from http://www.iluoghidelsociale.it/?page_id=1522
ExtractedDoc [fields={cinecatitle=Città in Tasca  «  i luoghi del sociale, url=http://www.iluoghidelsociale.it/?page_id=1522}, url=http://www.iluoghidelsociale.it/?page_id=1522, title=http://www.iluoghidelsociale.it/?page_id=1522, outlinks=[]]

and I'm satisfied because the attribute "cinecatitle" is just a clone of the example extraction you provided

**Comment by virivigio** [comment]
now the problem is: since the extractor is correct, what is the best way to troubleshoot why i do no see attributes being extracted?
I use mode 1

if I enable
log4j.logger.ir.co.bayan.simorq.zal=DEBUG
and
        <property>
          <name>plugin.includes</name>
          <value>protocol-http|urlfilter-regex|extractor|scoring-opic|urlnormalizer-(pass|regex|basic)</value>
        </property>
        <property>
          <name>extractor.file</name>
          <value>cineca-extractors.xml</value>
        </property>

i just see those lines
and no cinecatitle attribute is reported in solr or crawldb... what am I missing?

**Comment by virivigio** [comment]
thought https://issues.apache.org/jira/browse/NUTCH-779 could help but the cinecatitle is not passed...

**Comment by tahagh** [comment]
Make sure you added your fields in solrschema.xml of your "solr" server not the one that provided by nutch (and clearly don't forget to restart the server). Also check that without extractor plugin your documents get indexed correctly. After that, enable the extractor DEBUG, and check that during indexing the document is actually passed.
