### ISSUE TITLE
How do I get nutch to crawl outlinks only and not the urls for each fragment?

### ISSUE THREAD

**Issue by manjunathbharadwaj** [BayanGroup/nutch-custom-search#27]
Consider a site where I want to use fragments to extract data from a page. An example is here: http://www.trulia.com/directory/Alamogordo-agent--3450/

All I need is the name. I am running extractor as the only plugin which is parsing the page and removed all the "parse-*" plugins. My extractors.conf looks like this:

```xml
  <fields>
    <field name="Name" />
    <field name="url" />
  </fields>
  <documents>
    <document url="." engine="css">
      <fragment root=".col.cols10">
        <extract-to field="Name">
          <text>
            <expr value=".typeEmphasize.ellipsis_overflow.mvn.agent_name_link.pan.man" />
          </text>
        </extract-to>
        <extract-to field="url">
          <first>
            <attribute name="href">
              <expr value="a" />
            </attribute>
          </first>
        </extract-to>
     </fragment>
    </document>
    <document url="." engine="css">
      <fragment root=".col.cols16.mts.txtC">
      <outlinks>
          <link>
            <href>
              <attribute name="href">
                <expr value="a" />
              </attribute>
            </href>
          </link>
      </outlinks>
        <extract-to field="url">
          <url/>
        </extract-to>
      </fragment>
    </document>
```

When I run nutch thus: ./bin/crawl -i urls/ crawl 2, the first iteration runs on the link I have provided. The second iteration runs on the outlinks and the URLs that are returned. The only reason I need URLs returned from the extractor is to make them unique and have them indexed but I do not want to crawl them again since all the information I need is in the first page and I have already extracted information from it. I want the second and subsequent iterations to only crawl the outlinks returned from the extractor plugin.

I have tried numerous things to stop this.

1. regex-urlfilter.txt has     -^http://www.trulia.com/profile/
2. nutch-site.xml has
```xml
<property>
    <name>db.url.filters</name>
    <value>true</value>
    <description>Filter urls when updating crawldb</description>
</property>
```

and many more tweaks none of which have had the effect I want: to consider only outlinks for the next iteration and not the URL returned for the sake of making the fragment data distinct.

So, how do I tell nutch that the urls returned are not to be crawled in the second iteration and that the second iteration only needs to look at outlinks?

**Comment by tahagh** [comment]
Clearly if you have filtering plugins enabled, your approach (using regex-urlfilter.txt) must prevent nutch from crawling those urls (filtering is also applied during the generate phase). So, I suspect that there must be something else going on.

**Comment by manjunathbharadwaj** [comment]
Thanks Taha.
I investigated a bit more and saw that the generate command had "-noFilter" as an arg by default. I removed that and now the filtering is enabled in subsequent iterations.
