### ISSUE TITLE
Concatenate 2 fields into one

### ISSUE THREAD

**Issue by AndraDenis** [BayanGroup/nutch-custom-search#29]
Hello, 

I'm pretty new with Nutch and recently I've discovered your awesome plugin. The thing I want to do is to index nested objects, but I didn't managed to do that so I'm thinking of using your plugin to do it. 
Lets say I have two fields "product_name" and "number" and I want to concatenate them into one field: article_list. How can I do that?
I was thinking of something like this:

     <extract-to field="article_list">
		<for-each root="html body div#frame_wrapper div#frame_cnt div#box_cnt_tabcontainerID0.box_cnt_tabcontainer.product_table div.cnt_tabcontainer_panelset div.cnt_tabcontainer_panel ul.cnt_more_info_list.cnt_article_list li div">
		<concat delimiter=" ">
		<constant value="number"/>
                <text>
                    <expr value=".descr.rt span.lt" />
                </text>
		<constant value="product_name">
		 <text>
                    <expr value=".strong p" />
                </text>
		</concat>
		</for-each>
            </extract-to>
but it doesn't work. What should I do?

**Comment by tahagh** [comment]
It seems to me that your snippet must work correctly. May be it is a good idea to break it into parts (for instance first only extract numbers and see whether it works or not) to find the problematic part. By the work, I recommend using zal.extractor.tools jar (provided in the release section) for testing. You can call it in this way:
java -jar zal.extractor.toolsXXX.jar <your-url> <location-of-your-extractors.xml>

**Comment by AndraDenis** [comment]
When I run
java -jar zal.extractor.toolsXXX.jar your-url location-of-your-extractors.xml
I get the error: 
conf/extractors.xml: line 1: syntax error near unexpected token `newline'

Is there any way of concatenate 2 extings fields? I'll give you an example to understand well. If I have those 2 fileds

<extract-to field="title">
                <text>
                    <expr value="html body div#frame_wrapper div#frame_cnt div.box_2col div.box_cnt div.box_headline div.lt h1" />
                </text>
 </extract-to>
	    
	    <extract-to field="description">
                <text>
                    <expr value="html body div#frame_wrapper div#frame_cnt div.box_2col.space_b30 div.box_cnt p" />
                </text>
            </extract-to>

how can I concatenate them into one field?

**Comment by tahagh** [comment]
you can use field-value function to do so e.g.

```
<extract-to field="combine">
    <concat>
      <field-value field="title"/>
      <field-value field="desc"/>
    </concat>
</extract-to/>
```

also it seems something is wrong with your xml, may be it starts with a new
line

**Comment by AndraIonescu** [comment]
Why doesn't he plugin work for some websites?
