### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by AndraIonescu** [BayanGroup/nutch-custom-search#30]
Hello, 

I have this website: http://www.medtronic.com/for-healthcare-professionals/products-therapies/cardiovascular/coronary-stents/integrity-coronary-stent/index.htm and I want to index the image url, but it seems like it doesn't work. 

Can you take a look, please? I really need that url.

Thank you, 
Andra.

**Comment by tahagh** [comment]
Hi,
Would you please send your extractor.xml file. Also, did you check your log files? There might be some config problems.

**Comment by AndraIonescu** [comment]
This is my extractors.xml. It is very strange that it doesn't work on that website. 

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir http://raw.github.com/BayanGroup/nutch-custom-search/master/zal.extractor/src/main/resources/extractors.xsd">
	<fields>
		<field name="image"/>
	</fields>
	<documents>
		<document url="." engine="css">
			<extract-to field="image" >
					<attribute name="src">
                    				<expr value="html body div#wrapper div#container div#main div#main-content div#main-content-text div#main-content-intro div.intro-img-right p img"/>
                			 </attribute>
   			</extract-to>   
		</document>
	</documents>
</config>

**Comment by AndraIonescu** [comment]
On a second look, the extractors does work because I can see the constant added in solr, but the css selector doesn't work and I do not understand why. Can you take a look, please?
