### ISSUE TITLE
Css :not pseudo-class doesn't work

### ISSUE THREAD

**Issue by AndraIonescu** [BayanGroup/nutch-custom-search#32]
Hi, 

I tried to use the :not(.class-name) pseudo-class and it doesn't work. Is it not recognized by your plug-in or what is the problem?

Thanks!

**Comment by tahagh** [comment]
Hi,
The plugin internally uses the [jsoup](http://jsoup.org/) project for its css-selector processing. As far as I know jsoup supports this pseudo-class so the problem might lie somewhere else.
