### ISSUE TITLE
Ignore load-external-dtd declaration in xml

### ISSUE THREAD

**Issue by nithingit** [BayanGroup/nutch-custom-search#33]
I am downloading an xml and parsing it using your plugin,but in my xml there is a doctype declaration which points to an external dtd,because of this I am getting an error and not able to parse.Is there a way to specify a parameter so as to ignore this dtd.

For exanple when we parse using documentbuilder factory we can specify :
 DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
	    	      dbFactory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);

**Comment by tahagh** [comment]
Unfortunately, this is not directly supported but you can change the constructor of XPathEvaluator to add the above feature.
