### ISSUE TITLE
Limit the extraction of outlinks

### ISSUE THREAD

**Issue by wiradikusuma** [BayanGroup/nutch-custom-search#42]
I'm just getting started with Nutch, I'm using version 1.13.

How do I limit the extraction of outlinks, so that it's only extracted from certain whitelist/blacklist selector? E.g.

  * extract all outlinks from "div.menu"
  * do *not* extract any outlink from "div.footer" and "div.extra"

At the moment, the page I'm scraping from contains >500 outlinks, but I'm only interested in those that's in the "center" of the page.

If this is outside the functionality of this plugin (or not implemented yet), please let me know some starting points. Thanks!

**Comment by tahagh** [comment]
The whitelist mode is supported like this:

```
<document url=".">
	<outlinks>
		<link>
			<href>
				<resolve>
					<attribute name="href">
						<expr value="div.menu a"/>
					</attribute>
				</resolve>
			</href>
		</link>
	</outlinks>
</document>
```

But for the blacklist mode you must implement a new custom function.
