### ISSUE TITLE
extraction with xpath engin

### ISSUE THREAD

**Issue by moees** [BayanGroup/nutch-custom-search#9]
Hi.
I cannot extract data with the xpath engine. I tried with several sites and several pages. here's the example i'm using:
url:http://gsas.harvard.edu/
        expr value="//*[@id='home_right']/div[1]/div[1]/h2/a"

It works with the css engine:
     expr value=".header>h2>a" 

Can you please tell me what i'm doing wrong?
Thanks in advance

**Comment by ChanderG** [comment]
@moees Did you manage to get it working? I am having the same problem (Nutch 1.9).

**Comment by moees** [comment]
Hi ChanderG, sorry for answering late. I was tring to get it working in nutch 2 but i couldn't because the classe ParseResults is not included in nutch 2, and i didn't want to change the core source code. I will maybe manage to get it working in nutch 1 if i don't find a solution.
